openapi: 3.0.3
info:
  title: Data Repository Service
  version: 1.1.0
  x-logo:
    url: 'https://www.ga4gh.org/wp-content/themes/ga4gh-theme/gfx/GA-logo-horizontal-tag-RGB.svg'
  description:
    $ref: '../sources/md/front_matter.md'
  termsOfService: 'https://www.ga4gh.org/terms-and-conditions/'
  contact:
    name: GA4GH Cloud Work Stream
    email: ga4gh-cloud@ga4gh.org
  license:
    name: Apache 2.0
    url: 'https://raw.githubusercontent.com/ga4gh/data-repository-service-schemas/master/LICENSE'
servers:
  - url: https://{serverURL}/ga4gh/drs/v1
    variables:
      serverURL:
        default: drs.example.org
        description: >
          DRS server endpoints MUST be prefixed by the '/ga4gh/drs/v1' endpoint 
          path
security:
  - {}
  - BasicAuth: []
  - BearerAuth: []
tags:
  # Overview
  - name: Introduction
    description:
      $ref: ./tags/Introduction.md
  - name: DRS API Principles
    description:
      $ref: ./tags/DrsApiPrinciples.md
  - name: Authorization & Authentication
    description:
      $ref: ./tags/Auth.md

  # Operations
  - name: Objects

  # Models
  - name: AccessMethodModel
    x-displayName: AccessMethod
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/AccessMethod" />
  - name: AccessURLModel
    x-displayName: AccessURL
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/AccessURL" />
  - name: ChecksumModel
    x-displayName: Checksum
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Checksum" />
  - name: ContentsObjectModel
    x-displayName: ContentsObject
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ContentsObject" />
  - name: DrsObjectModel
    x-displayName: DrsObject
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/DrsObject" />
  - name: ErrorModel
    x-displayName: Error
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Error" />

  # Appendices
  - name: 'Appendix: Motivation'
    description:
      $ref: '../sources/md/appendix_motivation.md'
  - name: 'Appendix: Background Notes on DRS URIs'
    description:
      $ref: '../sources/md/appendix_background_notes_on_drs_uris.md'
  - name: 'Appendix: Compact Identifier-Based URIs'
    description:
      $ref: '../sources/md/appendix_compact_identifier_based_uris.md'
  - name: 'Appendix: Hostname-Based URIs'
    description:
      $ref: '../sources/md/appendix_hostname_based_uris.md'
x-tagGroups:
  - name: Overview
    tags:
      - Introduction
      - DRS API Principles
      - Authorization & Authentication
  - name: Operations
    tags:
      - Objects
  - name: Models
    tags:
      - AccessMethodModel
      - AccessURLModel
      - ChecksumModel
      - ContentsObjectModel
      - DrsObjectModel
      - ErrorModel
  

paths:
  /objects/{object_id}:
    get:
      summary: Get info about a DrsObject.
      description: >-
        Returns object metadata, and a list of access methods that can be used to fetch object bytes.
      operationId: GetObject
      parameters:
        - $ref: '#/components/parameters/objectId'
        - $ref: '#/components/parameters/expand'
      responses:
        200:
          $ref: '#/components/responses/200OkDrsObject'
        202:
          $ref: '#/components/responses/202Accepted'
        400:
          $ref: '#/components/responses/400BadRequest'
        401:
          $ref: '#/components/responses/401Unauthorized'
        403:
          $ref: '#/components/responses/403Forbidden'
        404:
          $ref: '#/components/responses/404NotFoundDrsObject'
        500:
          $ref: '#/components/responses/500InternalServerError'
      tags:
        - Objects
      x-swagger-router-controller: ga4gh.drs.server
  /objects/{object_id}/access/{access_id}:
    get:
      summary: Get a URL for fetching bytes
      description: >-
        Returns a URL that can be used to fetch the bytes of a `DrsObject`.


        This method only needs to be called when using an `AccessMethod` that contains an `access_id`
        (e.g., for servers that use signed URLs for fetching object bytes).
      operationId: GetAccessURL
      parameters:
        - $ref: '#/components/parameters/objectId'
        - $ref: '#/components/parameters/accessId'
      responses:
        200:
          $ref: '#/components/responses/200OkAccess'
        202:
          $ref: '#/components/responses/202Accepted'
        400:
          $ref: '#/components/responses/400BadRequest'
        401:
          $ref: '#/components/responses/401Unauthorized'
        403:
          $ref: '#/components/responses/403Forbidden'
        404:
          $ref: '#/components/responses/404NotFoundAccess'
        500:
          $ref: '#/components/responses/500InternalServerError'
      tags:
        - Objects
      x-swagger-router-controller: ga4gh.drs.server

components:
  schemas:
    Checksum:
      $ref: ./components/schemas/Checksum.yaml
    DrsObject:
      $ref: ./components/schemas/DrsObject.yaml
    AccessURL:
      $ref: ./components/schemas/AccessURL.yaml
    AccessMethod:
      $ref: ./components/schemas/AccessMethod.yaml
    Error:
      $ref: ./components/schemas/Error.yaml
    ContentsObject:
      $ref: ./components/schemas/ContentsObject.yaml

  parameters:
    objectId:
      in: path
      name: object_id
      required: true
      description: '`DrsObject` identifier'
      schema:
        type: string
    accessId:
      in: path
      name: access_id
      required: true
      description: An `access_id` from the `access_methods` list of a `DrsObject`
      schema:
        type: string
    expand:
      in: query
      name: expand
      schema:
        type: boolean
        example: false
      description: >-
        If false and the object_id refers to a bundle, then the ContentsObject array
        contains only those objects directly contained in the bundle. That is, if the
        bundle contains other bundles, those other bundles are not recursively
        included in the result.

        If true and the object_id refers to a bundle, then the entire set of objects
        in the bundle is expanded. That is, if the bundle contains aother bundles,
        then those other bundles are recursively expanded and included in the result.
        Recursion continues through the entire sub-tree of the bundle.

        If the object_id refers to a blob, then the query parameter is ignored.

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: |
        A valid authorization token must be passed in the 'Authorization' header,
        e.g. "Basic ${token_string}"
    BearerAuth:
      type: http
      scheme: bearer
      description:
        A valid authorization token must be passed in the 'Authorization' header,
        e.g. "Bearer ${token_string}"

  responses:
    200OkDrsObject:
      $ref: ./components/responses/200OkDrsObject.yaml
    200OkAccess:
      $ref: ./components/responses/200OkAccess.yaml
    202Accepted:
      $ref: ./components/responses/202Accepted.yaml
    400BadRequest:
      $ref: ./components/responses/400BadRequest.yaml
    401Unauthorized:
      $ref: ./components/responses/401Unauthorized.yaml
    403Forbidden:
      $ref: ./components/responses/403Forbidden.yaml
    404NotFoundDrsObject:
      $ref: ./components/responses/404NotFoundDrsObject.yaml
    404NotFoundAccess:
      $ref: ./components/responses/404NotFoundAccess.yaml
    500InternalServerError:
      $ref: ./components/responses/500InternalServerError.yaml
